twig:
    default_path: '%frontendRoot%/Resources/views'

twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        Contena\Frontend\Resources\views\components\: 'components/'
